### ISSUE TITLE
Go1.7.1で動かないようです

### ISSUE THREAD

**Issue by Konboi** [soh335/sliceflag#2]
詳しい原因は今調べていますがGoの最新バージョンで動かなくなっているようです
以下に`go test` を実行した際のログを載せておきます

```
$ go version
go version go1.7.1 darwin/amd64
$ go test .
--- FAIL: TestAll (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6ef56]

goroutine 17 [running]:
panic(0xfa7c0, 0x4201fe0b0)
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0x42028e180)
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/testing/testing.go:579 +0x25d
panic(0xfa7c0, 0x4201fe0b0)
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/soh335/sliceflag.(*durationSliceValue).String(0x42026a970, 0xfc4c0, 0x42026a970)
        /Users/yabuki-ryosuke/src/github.com/soh335/sliceflag/sliceflag.go:35 +0x46
flag.isZeroValue(0x4202885c0, 0x42026a300, 0x2, 0x11b10f)
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/flag/flag.go:393 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0x4202885c0)
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/flag/flag.go:467 +0x1d5
flag.(*FlagSet).VisitAll(0x42029bee8, 0x42029ac50)
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/flag/flag.go:323 +0x67
flag.(*FlagSet).PrintDefaults(0x42029bee8)
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/flag/flag.go:476 +0x46
github.com/soh335/sliceflag.TestAll(0x42028e180)
        /Users/yabuki-ryosuke/src/github.com/soh335/sliceflag/sliceflag_test.go:151 +0x23d5
testing.tRunner(0x42028e180, 0x12b5a0)
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
        /Users/yabuki-ryosuke/.brew/Cellar/go/1.7.1/libexec/src/testing/testing.go:646 +0x2ec
FAIL    github.com/soh335/sliceflag     0.011s
```

**Comment by soh335** [comment]
@Konboi 報告ありがとうございます。なおしました。

**Comment by Konboi** [comment]
迅速な対応ありがとうございます！
